FROM node:18-alpine AS builder

WORKDIR /workspace/frontend

COPY package*.json ./
RUN npm install


COPY . .

RUN npm run build -- --configuration=production


FROM nginx:alpine


COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /workspace/frontend/dist/atom-challenge-fe-template/browser /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
