version: '3.9'
services:
  frontend:
    container_name: todo-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  backend:
    container_name: todo-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
