name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build and test the frontend and backend container
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create .env file for the backend
      - name: Create .env file in backend
        run: |
          cd backend
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> .env
          echo "SA_KEY=${{ secrets.SA_KEY }}" >> .env
          echo "FIRESTORE_PROJECT_ID=${{ secrets.FIRESTORE_PROJECT_ID }}" >> .env
          echo "FIRESTORE_KEY_FILE=${{ secrets.FIRESTORE_KEY_FILE }}" >> .env
          cat .env
          cd ..

      # Create service-account.json file for the backend
      - name: Create service-account.json in backend
        run: |
          cd backend
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json
          cat service-account.json
          cd ..

      # Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          pwd
          ls -l
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }} -f Dockerfile.prod .
          cd ..
      
      # Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ github.sha }} -f Dockerfile.prod .
          cd ..

      # Upload images to Docker Hub
      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }}
      
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ github.sha }}

  # Job for deployment
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job only runs if the build job is successful
    
    steps:
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway CLI to path
        run: echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      - name: Log in to Railway
        run: railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}

      # Deploy Frontend Docker image to Railway
      - name: Deploy Frontend Docker image to Railway
        run: |
          railway service:deploy --project ${{ secrets.RAILWAY_PROJECT_ID }} \
          --service ${{ secrets.RAILWAY_SERVICE_ID_FRONTEND }} \
          --image ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }}
      
      # Deploy Backend Docker image to Railway
      - name: Deploy Backend Docker image to Railway
        run: |
          railway service:deploy --project ${{ secrets.RAILWAY_PROJECT_ID }} \
          --service ${{ secrets.RAILWAY_SERVICE_ID_BACKEND }} \
          --image ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ github.sha }}