name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build and test the frontend and backend container
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create .env file for the backend
      - name: Create .env file in backend
        run: |
          cd backend
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> .env
          echo "FIRESTORE_PROJECT_ID=${{ secrets.FIRESTORE_PROJECT_ID }}" >> .env
          echo "FIRESTORE_PRIVATE_KEY=${{ secrets.FIRESTORE_PRIVATE_KEY }}" >> .env
          echo "FIRESTORE_CLIENT_EMAIL=${{ secrets.FIRESTORE_CLIENT_EMAIL }}" >> .env
          cd ..

      # Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }} \
                 -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest \
                 -f Dockerfile.prod .
          cd ..
      
      # Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ github.sha }} \
                 -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest \
                 -f Dockerfile.prod .
          cd ..

      # Upload images to Docker Hub
      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
      
      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

  # Job for deployment
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Show Deployment Instructions
        run: |
          echo "🚀 Images have been successfully pushed to Docker Hub with the 'latest' tag."
          echo "🛠️ Go to Railway and manually execute 'Deploy from Docker Hub' for each service:"
          echo "👉 Frontend: https://railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/service/${{ secrets.RAILWAY_SERVICE_ID_FRONTEND }}"
          echo "👉 Backend: https://railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/service/${{ secrets.RAILWAY_SERVICE_ID_BACKEND }}"
              